# Generated by Django 5.2.16 on 2026-08-09 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_type', models.CharField(db_index=True, default='desktop', max_length=32)),
                ('browser', models.CharField(blank=True, default='', max_length=64)),
                ('os_name', models.CharField(blank=True, default='', max_length=64)),
                ('country', models.CharField(blank=True, db_index=True, default='Unknown', max_length=64)),
                ('referrer', models.TextField(blank=True, default='')),
                ('ref_code', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('page_view_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visitor Session',
                'verbose_name_plural': 'Visitor Sessions',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('download_pdf', 'Download PDF Resume'), ('export_json', 'Export JSON Resume'), ('print_resume', 'Print Web Resume'), ('select_role', 'Target Role Filtered'), ('expand_arch', 'Project Arch Expanded'), ('ask_ai', 'AI Copilot Query'), ('verify_cert', 'AWS Certification Verified'), ('custom', 'Custom Interaction')], db_index=True, default='page_view', max_length=32)),
                ('path', models.CharField(db_index=True, default='/', max_length=255)),
                ('event_target', models.CharField(blank=True, default='', max_length=255)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='analytics.visitorsession')),
            ],
            options={
                'verbose_name': 'Telemetry Event',
                'verbose_name_plural': 'Telemetry Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
