# Generated by Django 5.2.16 on 2026-07-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Harsh Tripathi', max_length=255)),
                ('title', models.CharField(default='Backend & Cloud Engineer', max_length=255)),
                ('email', models.EmailField(default='tripathiharsh324@gmail.com', max_length=254)),
                ('location', models.CharField(default='India', max_length=255)),
                ('tagline', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, max_length=1024)),
                ('resume_url', models.URLField(blank=True, max_length=1024)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('github_url', models.URLField(default='https://github.com/Harsh324')),
                ('linkedin_url', models.URLField(default='https://linkedin.com/in/harsh324')),
                ('twitter_url', models.URLField(default='https://x.com/harsh324')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
