# Generated by Django 5.2.16 on 2026-08-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='engineering_focus',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of engineering specializations'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='open_to_work',
            field=models.BooleanField(default=True, help_text='Career availability status toggle'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of target career roles'),
        ),
    ]
