# Generated by Django 5.2.16 on 2026-09-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['order', '-date', 'title']},
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='is_milestone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='target_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='category',
            field=models.CharField(default='Career', max_length=100),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
