# Generated by Django 5.2.16 on 2026-07-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('architecture', models.TextField(blank=True)),
                ('lessons_learned', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='active', max_length=50)),
                ('repository', models.URLField(blank=True)),
                ('demo', models.URLField(blank=True)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('architecture_images', models.JSONField(blank=True, default=list)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('roadmap', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tech_stack', models.ManyToManyField(blank=True, related_name='projects', to='technologies.technology')),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
