# Generated by Django 5.2.16 on 2026-08-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
