# Generated by Django 5.2.16 on 2026-08-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='architecture_flow',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='docs_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('application', 'Application / Product'), ('infrastructure', 'Infrastructure & Homelab'), ('platform', 'Platform & Tooling'), ('open_source', 'Open Source Library'), ('experiment', 'Research & Experiment')], default='application', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='target_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_outcome',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_development', 'In Development'), ('active', 'Active'), ('deployed', 'Deployed'), ('archived', 'Archived')], default='active', max_length=50),
        ),
    ]
