# Generated by Django 5.2.16 on 2026-07-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('issuer', models.CharField(max_length=255)),
                ('credential_url', models.URLField(blank=True)),
                ('issue_date', models.CharField(max_length=50)),
                ('expiry_date', models.CharField(blank=True, max_length=50)),
                ('badge', models.URLField(blank=True, max_length=1024)),
                ('badge_file', models.ImageField(blank=True, null=True, upload_to='certifications/badges/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_skills', models.ManyToManyField(blank=True, related_name='certifications', to='skills.skill')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
