# Generated by Django 5.2.16 on 2026-09-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
        ('experiences', '0003_alter_experience_options_experience_internal_notes_and_more'),
        ('projects', '0004_project_architecture_flow_project_docs_url_and_more'),
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['order', '-issue_date', 'name']},
        ),
        migrations.AddField(
            model_name='certification',
            name='category',
            field=models.CharField(blank=True, default='Cloud & Infrastructure', max_length=100),
        ),
        migrations.AddField(
            model_name='certification',
            name='credential_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='does_not_expire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certification',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certification',
            name='related_experiences',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='experiences.experience'),
        ),
        migrations.AddField(
            model_name='certification',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='projects.project'),
        ),
        migrations.AddField(
            model_name='certification',
            name='related_technologies',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='technologies.technology'),
        ),
        migrations.AddField(
            model_name='certification',
            name='target_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='certification',
            name='verification_status',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('in_progress', 'In Progress'), ('expired', 'Expired')], default='verified', max_length=50),
        ),
        migrations.AlterField(
            model_name='certification',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
