# Generated by Django 5.2.16 on 2026-07-30 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('employment_type', models.CharField(default='full-time', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(default='present', max_length=50)),
                ('current_position', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=True)),
                ('mission', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('executive_overview', models.TextField(blank=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('focus_areas', models.JSONField(blank=True, default=list)),
                ('tech_groups', models.JSONField(blank=True, default=dict)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('team', models.CharField(blank=True, max_length=255)),
                ('ownership', models.TextField(blank=True)),
                ('lessons_learned', models.JSONField(blank=True, default=list)),
                ('architecture_diagram', models.URLField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='companies.company')),
                ('related_projects', models.ManyToManyField(blank=True, related_name='experiences', to='projects.project')),
                ('technologies', models.ManyToManyField(blank=True, related_name='experiences', to='technologies.technology')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
