# Generated by Django 5.2.16 on 2026-08-29 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='current_position',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='experience',
            name='featured',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
