# Generated by Django 5.2.16 on 2026-07-30 04:14

import apps.media_assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.media_assets.models.get_upload_path)),
                ('media_type', models.CharField(choices=[('company_logo', 'Company Logo'), ('screenshot', 'Screenshot'), ('architecture_diagram', 'Architecture Diagram'), ('resume', 'Resume'), ('certificate', 'Certificate'), ('profile_image', 'Profile Image'), ('opengraph_image', 'OpenGraph Image'), ('other', 'Other Asset')], default='other', max_length=50)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
