# Generated by Django 5.2.16 on 2026-09-02 04:36

import apps.media_assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_alter_certification_options_certification_category_and_more'),
        ('education', '0002_alter_education_options_education_currently_studying_and_more'),
        ('experiences', '0003_alter_experience_options_experience_internal_notes_and_more'),
        ('media_assets', '0001_initial'),
        ('projects', '0004_project_architecture_flow_project_docs_url_and_more'),
        ('skills', '0003_skill_evidence_context_skill_internal_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaasset',
            options={'ordering': ['display_order', '-is_featured', '-created_at'], 'verbose_name': 'Media Asset', 'verbose_name_plural': 'Media Assets'},
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='media_type',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Descriptive alternative text for accessibility (required for public images).', max_length=500),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='asset_type',
            field=models.CharField(choices=[('profile', 'Profile Image / Avatar'), ('project_image', 'Project Screenshot / Visual'), ('project_logo', 'Project Logo / Icon'), ('architecture_diagram', 'Architecture / System Diagram'), ('certification', 'Certification Badge / Credential'), ('education', 'Education / Degree / Diploma'), ('company_logo', 'Company Logo'), ('resume', 'Resume / CV Document'), ('document', 'Technical Document / Whitepaper'), ('social_preview', 'Social Preview / OpenGraph Card'), ('other', 'Other Asset')], db_index=True, default='project_image', max_length=50),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='external_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='related_certifications',
            field=models.ManyToManyField(blank=True, related_name='media_assets', to='certifications.certification'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='related_education',
            field=models.ManyToManyField(blank=True, related_name='media_assets', to='education.education'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='related_experiences',
            field=models.ManyToManyField(blank=True, related_name='media_assets', to='experiences.experience'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='media_assets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='related_skills',
            field=models.ManyToManyField(blank=True, related_name='media_assets', to='skills.skill'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='target_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.media_assets.models.get_media_upload_path),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
