# Generated by Django 5.2.16 on 2026-08-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
    ]
