# Generated by Django 5.2.16 on 2026-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_alter_experience_options_experience_internal_notes_and_more'),
        ('projects', '0004_project_architecture_flow_project_docs_url_and_more'),
        ('skills', '0002_skill_is_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='evidence_context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(choices=[('expert', 'Expert / Staff Level'), ('advanced', 'Advanced / Production Proficient'), ('proficient', 'Proficient / Working Knowledge'), ('familiar', 'Familiar / Basic'), ('learning', 'Active Learning / Exploring')], default='advanced', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='related_experiences',
            field=models.ManyToManyField(blank=True, related_name='related_skills', to='experiences.experience'),
        ),
        migrations.AddField(
            model_name='skill',
            name='related_projects',
            field=models.ManyToManyField(blank=True, related_name='related_skills', to='projects.project'),
        ),
        migrations.AddField(
            model_name='skill',
            name='target_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Backend Engineering', 'Backend Engineering'), ('Cloud & Infrastructure', 'Cloud & Infrastructure'), ('Architecture & Distributed Systems', 'Architecture & Distributed Systems'), ('Databases & Caching', 'Databases & Caching'), ('AI & Data', 'AI & Data'), ('DevOps & CI/CD', 'DevOps & CI/CD'), ('Supporting Technologies', 'Supporting Technologies')], default='Backend Engineering', max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='experience_level',
            field=models.CharField(blank=True, default='Advanced', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='is_core',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='years',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=4),
        ),
    ]
