# Generated by Django 5.2.16 on 2026-07-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('logo', models.URLField(blank=True, max_length=1024)),
                ('logo_file', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('careers', models.URLField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=255)),
                ('company_size', models.CharField(blank=True, max_length=100)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('founded', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
