# Generated by Django 5.2.16 on 2026-09-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['order', '-end_date', 'institution'], 'verbose_name_plural': 'Education Records'},
        ),
        migrations.AddField(
            model_name='education',
            name='currently_studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='education',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='education',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='education',
            name='target_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='education',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
