# Generated by Django 5.2.16 on 2026-07-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_identifier', models.CharField(help_text="e.g. 'home', 'experience', 'projects', 'skills'", max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.URLField(blank=True, max_length=1024)),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=50)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots', models.CharField(default='index, follow', max_length=100)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata Records',
            },
        ),
    ]
